# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-23 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_authors_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
