# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-23 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='desc',
            field=models.TextField(default='Description still needed'),
            preserve_default=False,
        ),
    ]
